export const STANDARD_DATE_FORMAT = 'YYYY-MM-DD'
export const STANDARD_TIME_FORMAT = 'HH:mm'
export const FULL_DATE = 'Do MMM YYYY'
export const DATE_NUMBER = 'YYYYMMDD'
export const DATE_TIME = 'ddd Do MMM HH:mm'
export const DATE_INTERNAL_FORMAT = 'YYYY-MM-DD'
export const TIME_INTERNAL_FORMAT = 'HH:mm'
